namespace BumbleBeeFoundation.Models
{
    public class FundingRequestViewModel
    {
        public int RequestID { get; set; } // The ID of the request (auto-generated by the DB)
        public int CompanyID { get; set; } // The ID of the company making the request
        public string ProjectDescription { get; set; } // A description of the project
        public decimal RequestedAmount { get; set; } // The amount of funding requested
        public string ProjectImpact { get; set; } // Description of how the project will impact the company/industry
        public string Status { get; set; } = "Pending"; // E.g., Pending, Approved, Rejected
        public DateTime SubmittedAt { get; set; } // Timestamp of when the request was submitted
    }

}
